plugins {
    id("maven-publish")
    id("java-platform")
}

javaPlatform {
    allowDependencies()
}

dependencies {
    val kotlinVersion = property("KOTLIN_VERSION").toString()
    val agpVersion = property("AGP_VERSION").toString()
    val kspVersion = property("KSP_VERSION").toString()
    // https://developer.android.com/jetpack/compose/bom/bom-mapping
    api(platform("androidx.compose:compose-bom:2024.02.00"))
    api(platform("com.fasterxml.jackson:jackson-bom:2.16.0"))
    api(platform("com.google.firebase:firebase-bom:32.7.0"))
    api(platform("com.squareup.okhttp3:okhttp-bom:4.12.0"))
    api(platform("io.coil-kt:coil-bom:2.5.0"))
    api(platform("io.github.jan-tennert.supabase:bom:1.4.7"))
    api(platform("io.insert-koin:koin-bom:3.5.3"))
    api(platform("org.junit:junit-bom:5.10.1"))
    api(platform("org.mockito:mockito-bom:5.8.0"))
    api(platform("org.jetbrains.kotlin:kotlin-bom:$kotlinVersion"))
    api(platform("org.ow2.asm:asm-bom:9.6"))
    constraints {
        fun plugin(id: String, version: String) = "$id:$id.gradle.plugin:$version"
        api(plugin("androidx.benchmark", "1.2.2"))
        api(plugin("com.android.application", agpVersion))
        api(plugin("com.android.library", agpVersion))
        api(plugin("org.jetbrains.kotlin.jvm", kotlinVersion))
        api(plugin("org.jetbrains.kotlin.android", kotlinVersion))
        api(plugin("org.jetbrains.kotlin.plugin.serialization", kotlinVersion))
        api(plugin("org.jetbrains.kotlin.plugin.parcelize", kotlinVersion))
        api(plugin("com.google.android.libraries.mapsplatform.secrets-gradle-plugin", "2.0.1"))
        api(plugin("com.google.devtools.ksp", kspVersion))
        api(plugin("com.google.dagger.hilt.android", "2.47"))

        // https://developer.android.com/jetpack/androidx/releases/activity
        // https://maven.google.com/web/index.html
        api("androidx.activity:activity-ktx:1.8.2")
        api("androidx.activity:activity-compose:1.8.2")
        api("androidx.ads:ads-identifier:1.0.0-alpha05")
        api("androidx.annotation:annotation:1.7.1")
        api("androidx.annotation:annotation-experimental:1.3.1")
        api("androidx.appcompat:appcompat:1.6.1")
        api("androidx.appcompat:appcompat-resources:1.6.1")
        api("androidx.arch.core:core-testing:2.2.0")
        api("androidx.autofill:autofill:1.1.0")
        api("androidx.benchmark:benchmark-macro-junit4:1.2.2")
        api("androidx.biometric:biometric:1.1.0")
        api("androidx.bluetooth:bluetooth:1.0.0-alpha02")
        api("androidx.camera:camera-core:1.3.1")
        api("androidx.camera:camera-camera2:1.3.1")
        api("androidx.camera:camera-lifecycle:1.3.1")
        api("androidx.camera:camera-video:1.3.1")
        api("androidx.camera:camera-view:1.3.1")
        api("androidx.camera:camera-mlkit-vision:1.3.1")
        api("androidx.camera:camera-extensions:1.3.1")
        api("androidx.constraintlayout:constraintlayout:2.1.4")
        api("androidx.constraintlayout:constraintlayout-compose:1.0.1")
        api("androidx.core:core-ktx:1.12.0")
        api("androidx.core:core-role:1.0.0")
        api("androidx.core:core-animation:1.0.0-rc01")
        api("androidx.core:core-animation-testing:1.0.0-rc01")
        api("androidx.core:core-performance:1.0.0-rc01")
        api("androidx.core:core-google-shortcuts:1.1.0")
        api("androidx.core:core-remoteviews:1.0.0")
        api("androidx.core:core-splashscreen:1.1.0-alpha02")
        api("androidx.credentials:credentials:1.3.0-alpha01")
        api("androidx.datastore:datastore-preferences:1.0.0")
        api("androidx.datastore:datastore:1.0.0")
        api("androidx.dynamicanimation:dynamicanimation-ktx:1.1.0-alpha03")
        api("androidx.emoji2:emoji2:1.4.0")
        api("androidx.emoji2:emoji2-views:1.4.0")
        api("androidx.emoji2:emoji2-views-helper:1.4.0")
        api("androidx.exifinterface:exifinterface:1.3.7")
        api("androidx.heifwriter:heifwriter:1.1.0-alpha02")
        api("androidx.hilt:hilt-navigation-compose:1.1.0")
        api("androidx.hilt:hilt-work:1.1.0")
        api("androidx.hilt:hilt-compiler:1.1.0")
        api("androidx.lifecycle:lifecycle-compiler:2.6.2")
        api("androidx.lifecycle:lifecycle-livedata-ktx:2.6.2")
        api("androidx.lifecycle:lifecycle-process:2.6.2")
        api("androidx.lifecycle:lifecycle-reactivestreams-ktx:2.6.2")
        api("androidx.lifecycle:lifecycle-runtime-compose:2.6.2")
        api("androidx.lifecycle:lifecycle-runtime-ktx:2.6.2")
        api("androidx.lifecycle:lifecycle-runtime-testing:2.6.2")
        api("androidx.lifecycle:lifecycle-service:2.6.2")
        api("androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2")
        api("androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2")
        api("androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.2")
        api("androidx.navigation:navigation-compose:2.6.0")
        api("androidx.media3:media3-exoplayer:1.1.0")
        api("androidx.media3:media3-exoplayer-dash:1.1.0")
        api("androidx.media3:media3-exoplayer-hls:1.1.0")
        api("androidx.media3:media3-exoplayer-rtsp:1.1.0")
        api("androidx.media3:media3-exoplayer-ima:1.1.0")
        api("androidx.media3:media3-datasource-cronet:1.1.0")
        api("androidx.media3:media3-datasource-okhttp:1.1.0")
        api("androidx.media3:media3-datasource-rtmp:1.1.0")
        api("androidx.media3:media3-ui:1.1.0")
        api("androidx.media3:media3-ui-leanback:1.1.0")
        api("androidx.media3:media3-session:1.1.0")
        api("androidx.media3:media3-extractor:1.1.0")
        api("androidx.media3:media3-cast:1.1.0")
        api("androidx.media3:media3-exoplayer-workmanager:1.1.0")
        api("androidx.media3:media3-transformer:1.1.0")
        api("androidx.media3:media3-test-utils:1.1.0")
        api("androidx.media3:media3-test-utils-robolectric:1.1.0")
        api("androidx.media3:media3-database:1.1.0")
        api("androidx.media3:media3-decoder:1.1.0")
        api("androidx.media3:media3-datasource:1.1.0")
        api("androidx.media3:media3-common:1.1.0")
        api("androidx.metrics:metrics-performance:1.0.0-alpha04")
        api("androidx.paging:paging-runtime:3.2.1")
        api("androidx.paging:paging-common:3.2.1")
        api("androidx.paging:paging-compose:3.3.0-alpha02")
        api("androidx.preference:preference-ktx:1.2.1")
        api("androidx.profileinstaller:profileinstaller:1.3.1")
        api("androidx.room:room-runtime:2.6.1")
        api("androidx.room:room-compiler:2.6.1")
        api("androidx.room:room-guava:2.6.1")
        api("androidx.room:room-testing:2.6.1")
        api("androidx.room:room-paging:2.6.1")
        api("androidx.security.crypto:security-app-authenticator:1.1.0-alpha03")
        api("androidx.security.crypto:security-crypto:1.1.0-alpha06")
        api("androidx.security.crypto:security-identity-credential:1.1.0-alpha03")
        api("androidx.startup:startup-runtime:1.2.0-alpha02")
        api("androidx.test:core-ktx:1.5.0")
        api("androidx.test:orchestrator:1.4.2")
        api("androidx.test.espresso:espresso-core:3.5.1")
        api("androidx.test.ext:junit:1.1.5")
        api("androidx.test.ext:runner:1.5.2")
        api("androidx.test.ext:truth:1.5.0")
        api("androidx.test.uiautomator:uiautomator:2.3.0-beta01")
        api("androidx.tracing:tracing-ktx:1.2.0")
        api("androidx.transition:transition-ktx:1.4.1")
        api("androidx.viewpager2:viewpager2:1.0.0")
        api("androidx.webkit:webkit:1.9.0")
        api("androidx.window:window:1.2.0")
        api("androidx.window:window-testing:1.2.0")
        api("androidx.window.extensions.core:core:1.0.0")
        api("androidx.work:work-runtime-ktx:2.9.0")
        api("androidx.work:work-gcm:2.9.0")
        api("androidx.work:work-testing:2.9.0")
        api("androidx.work:work-multiprocess:2.9.0")
        api("app.softwork:kotlinx-serialization-csv:0.0.16")
        api("app.softwork:kotlinx-serialization-flf:0.0.16")
        api("ch.acra:acra-advanced-scheduler:5.11.3")
        api("ch.acra:acra-core:5.11.3")
        api("ch.acra:acra-dialog:5.11.3")
        api("ch.acra:acra-http:5.11.3")
        api("ch.acra:acra-limiter:5.11.3")
        api("ch.acra:acra-mail:5.11.3")
        api("ch.acra:acra-notification:5.11.3")
        api("ch.acra:acra-toast:5.11.3")
        api("com.airbnb.android:lottie:6.2.0")
        api("com.akuleshov7:ktoml-core:0.5.1")
        api("com.akuleshov7:ktoml-file:0.5.1")
        api("com.alibaba.fastjson2:fastjson2:2.0.46")
        api("com.alibaba:fastjson:2.0.46")
        api("com.github.bumptech.glide:glide:4.16.0")
        api("io.github.pdvrieze.xmlutil:serialization:0.86.3")
        api("io.github.pdvrieze.xmlutil:serialization-jvm:0.86.3")
        api("io.github.pdvrieze.xmlutil:serialization-android:0.86.3")
        api("io.github.pdvrieze.xmlutil:serialization-js:0.86.3")
        api("com.github.PhilJay:MPAndroidChart:v3.1.0")
        api("com.google.accompanist:accompanist-drawablepainter:0.32.0")
        api("com.google.accompanist:accompanist-permissions:0.32.0")
        api("com.google.accompanist:accompanist-systemuicontroller:0.32.0")
        api("com.google.android.gms:play-services-maps:18.1.0")
        api("com.google.android.libraries.places:places:3.2.0")
        api("com.google.android.material:material:1.10.0")
        api("com.google.code.gson:gson:2.10.1")
        api("com.google.dagger:hilt-android:2.47")
        api("com.google.dagger:hilt-android-compiler:2.47")
        api("com.google.dagger:hilt-compiler:2.47")
        api("com.google.dagger:hilt-android-testing:2.47")
        api("com.google.devtools.ksp:symbol-processing-api:1.9.20-1.0.14")
        api("com.google.maps.android:maps-compose:2.11.4")
        api("com.google.maps.android:maps-ktx:5.0.0")
        api("com.google.zxing:android-core:3.5.2")
        api("com.google.zxing:android-integration:3.5.2")
        api("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
        api("com.jakewharton.timber:timber:5.0.1")
        api("com.squareup:javapoet:1.13.0")
        api("com.squareup:kotlinpoet:1.15.3")
        api("com.squareup.leakcanary:leakcanary-android:2.12")
        api("com.squareup.retrofit2:adapter-rxjava3:2.9.0")
        api("com.squareup.retrofit2:converter-gson:2.9.0")
        api("com.squareup.retrofit2:converter-jackson:2.9.0")
        api("com.squareup.retrofit2:converter-protobuf:2.9.0")
        api("com.squareup.retrofit2:retrofit:2.9.0")
        api("com.squareup.retrofit2:retrofit-mock:2.9.0")
        api("commons-io:commons-io:2.15.1")
        api("commons-codec:commons-codec:1.16.0")
        api("commons-logging:commons-logging:1.3.0")
        api("io.ktor:ktor-client-android:2.3.6")
        api("io.reactivex.rxjava3:rxjava:3.1.8")
        api("io.reactivex.rxjava3:rxandroid:3.0.2")
        api("junit:junit:4.13.2")
        api("net.mamoe.yamlkt:yamlkt:0.13.0")
        api("org-apache.commons:commons-lang3:3.14.0")
        api("org-apache.commons:commons-collections4:4.4")
        api("org.aspectj:aspect-core:3.24.2")
        api("org.javassist:javassist:3.30.1-GA")
        api("org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.7")
        api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0-RC2")
        api("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0-RC2")
        api("org.jetbrains.kotlinx:kotlinx-datetime:0.5.0")
        api("org.jetbrains.kotlinx:kotlinx-io-core:0.3.1")
        api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
        api("org.jetbrains.kotlinx:kotlinx-serialization-json-okio:1.5.1")
        api("org.jetbrains.kotlinx:kotlinx-serialization-json-hocon:1.5.1")
        api("org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.5.1")
        api("org.jetbrains.kotlinx:kotlinx-serialization-cbor:1.5.1")
        api("org.jetbrains.kotlinx:kotlinx-serialization-properties:1.5.1")
        api("org.jooq:jool:0.9.15")
        api("org.jooq:joor:0.9.15")
        api("org.jooq:joor-java-8:0.9.15")
        api("org.jsoup:jsoup:1.17.1")
        api("org.robolectric:android-all:14-robolectric-10818077")
        api("org.robolectric:robolectric:4.11.1")
        api("org.robolectric:sandbox:4.11.1")
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            version = project.version.toString()
            from(components.getByName("javaPlatform"))
        }
    }
}

tasks.registerLogDependencies()
