plugins {
    id("maven-publish")
    id("java-platform")
}

javaPlatform {
    allowDependencies()
}

dependencies {
    val kotlinVersion = System.getProperty("kotlin_version")
    val agpVersion = System.getProperty("agp_version")
    api(platform("androidx.compose:compose-bom:2023.10.01"))
    api(platform("com.fasterxml.jackson:jackson-bom:2.16.0"))
    api(platform("com.google.firebase:firebase-bom:32.7.0"))
    api(platform("com.squareup.okhttp3:okhttp-bom:4.12.0"))
    api(platform("io.coil-kt:coil-bom:2.5.0"))
    api(platform("io.github.jan-tennert.supabase:bom:1.4.7"))
    api(platform("io.insert-koin:koin-bom:3.5.3"))
    api(platform("org.junit:junit-bom:5.10.1"))
    api(platform("org.mockito:mockito-bom:5.8.0"))
    api(platform("org.jetbrains.kotlin:kotlin-bom:$kotlinVersion"))
    api(platform("org.ow2.asm:asm-bom:9.6"))
    constraints {
        fun plugin(id: String, version: String) = "$id:$id.gradle.plugin:$version"
        fun kotlin(name: String) = "org.jetbrains.kotlin.$name"
        api(plugin("androidx.benchmark", "1.2.2"))
        api(plugin("com.android.application", agpVersion))
        api(plugin("com.android.library", agpVersion))
        api(plugin(kotlin("jvm"), kotlinVersion))
        api(plugin(kotlin("android"), kotlinVersion))
        api(plugin(kotlin("plugin.serialization"), kotlinVersion))
        api(plugin(kotlin("plugin.parcelize"), kotlinVersion))
        api(plugin("com.google.android.libraries.mapsplatform.secrets-gradle-plugin", "2.0.1"))
        api(plugin("com.google.devtools.ksp", "1.9.21-1.0.15"))
        val hiltVersion = "2.47"
        api(plugin("com.google.dagger.hilt.android", hiltVersion))

        api("androidx.activity:activity-ktx:1.8.2")
        api("androidx.activity:activity-compose:1.8.0")
        api("androidx.ads:ads-identifier:1.0.0-alpha05")
        api("androidx.annotation:annotation:1.7.1")
        api("androidx.annotation:annotation-experimental:1.3.1")
        api("androidx.appcompat:appcompat:1.6.1")
        api("androidx.appcompat:appcompat-resources:1.6.1")
        api("androidx.arch.core:core-testing:2.2.0")
        api("androidx.benchmark:benchmark-macro-junit4:1.2.2")
        api("androidx.biometric:biometric:1.1.0")
        api("androidx.bluetooth:bluetooth:1.0.0-alpha02")
        "1.3.1".let {
            api("androidx.camera:camera-core:$it")
            api("androidx.camera:camera-camera2:$it")
            api("androidx.camera:camera-lifecycle:$it")
            api("androidx.camera:camera-video:$it")
            api("androidx.camera:camera-view:$it")
            api("androidx.camera:camera-mlkit-vision:$it")
            api("androidx.camera:camera-extensions:$it")
        }
        api("androidx.core:core-ktx:1.12.0")
        api("androidx.core:core-role:1.0.0")
        api("androidx.core:core-animation:1.0.0-rc01")
        api("androidx.core:core-animation-testing:1.0.0-rc01")
        api("androidx.core:core-performance:1.0.0-rc01")
        api("androidx.core:core-google-shortcuts:1.1.0")
        api("androidx.core:core-remoteviews:1.0.0")
        api("androidx.core:core-splashscreen:1.1.0-alpha02")
        api("androidx.credentials:credentials:1.3.0-alpha01")
        val dataStoreVersion = "1.0.0"
        api("androidx.datastore:datastore-preferences:$dataStoreVersion")
        api("androidx.datastore:datastore:$dataStoreVersion")
        api("androidx.dynamicanimation:dynamicanimation-ktx:1.1.0-alpha03")
        val emoji2Version = "1.4.0"
        api("androidx.emoji2:emoji2:$emoji2Version")
        api("androidx.emoji2:emoji2-views:$emoji2Version")
        api("androidx.emoji2:emoji2-views-helper:$emoji2Version")
        api("androidx.exifinterface:exifinterface:1.3.7")
        api("androidx.heifwriter:heifwriter:1.1.0-alpha02")
        api("androidx.hilt:hilt-navigation-compose:1.1.0")
        api("androidx.hilt:hilt-work:1.1.0")
        api("androidx.hilt:hilt-compiler:1.1.0")
        val lifecycleVersion = "2.6.2"
        api("androidx.lifecycle:lifecycle-compiler:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-livedata-ktx:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-process:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-runtime-compose:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-runtime-testing:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-service:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycleVersion")
        api("androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycleVersion")
        api("androidx.navigation:navigation-compose:2.6.0")
        val media3Version = "1.1.0"
        api("androidx.media3:media3-exoplayer:$media3Version")
        api("androidx.media3:media3-exoplayer-dash:$media3Version")
        api("androidx.media3:media3-exoplayer-hls:$media3Version")
        api("androidx.media3:media3-exoplayer-rtsp:$media3Version")
        api("androidx.media3:media3-exoplayer-ima:$media3Version")
        api("androidx.media3:media3-datasource-cronet:$media3Version")
        api("androidx.media3:media3-datasource-okhttp:$media3Version")
        api("androidx.media3:media3-datasource-rtmp:$media3Version")
        api("androidx.media3:media3-ui:$media3Version")
        api("androidx.media3:media3-ui-leanback:$media3Version")
        api("androidx.media3:media3-session:$media3Version")
        api("androidx.media3:media3-extractor:$media3Version")
        api("androidx.media3:media3-cast:$media3Version")
        api("androidx.media3:media3-exoplayer-workmanager:$media3Version")
        api("androidx.media3:media3-transformer:$media3Version")
        api("androidx.media3:media3-test-utils:$media3Version")
        api("androidx.media3:media3-test-utils-robolectric:$media3Version")
        api("androidx.media3:media3-database:$media3Version")
        api("androidx.media3:media3-decoder:$media3Version")
        api("androidx.media3:media3-datasource:$media3Version")
        api("androidx.media3:media3-common:$media3Version")
        api("androidx.metrics:metrics-performance:1.0.0-alpha04")
        api("androidx.paging:paging-runtime:3.2.1")
        api("androidx.paging:paging-common:3.2.1")
        api("androidx.paging:paging-compose:3.3.0-alpha02")
        api("androidx.preference:preference-ktx:1.2.1")
        api("androidx.profileinstaller:profileinstaller:1.3.1")
        val roomVersion = "2.6.1"
        api("androidx.room:room-runtime:$roomVersion")
        api("androidx.room:room-compiler:$roomVersion")
        api("androidx.room:room-guava:$roomVersion")
        api("androidx.room:room-testing:$roomVersion")
        api("androidx.room:room-paging:$roomVersion")
        api("androidx.security.crypto:security-app-authenticator:1.1.0-alpha03")
        api("androidx.security.crypto:security-crypto:1.1.0-alpha06")
        api("androidx.security.crypto:security-identity-credential:1.1.0-alpha03")
        api("androidx.startup:startup-runtime:1.2.0-alpha02")
        api("androidx.test:core-ktx:1.5.0")
        api("androidx.test:orchestrator:1.4.2")
        api("androidx.test.espresso:espresso-core:3.5.1")
        api("androidx.test.ext:junit:1.1.5")
        api("androidx.test.ext:runner:1.5.2")
        api("androidx.test.ext:truth:1.5.0")
        api("androidx.test.uiautomator:uiautomator:2.3.0-beta01")
        api("androidx.tracing:tracing-ktx:1.2.0")
        api("androidx.transition:transition-ktx:1.4.1")
        api("androidx.viewpager2:viewpager2:1.0.0")
        api("androidx.webkit:webkit:1.9.0")
        api("androidx.window:window:1.2.0")
        api("androidx.window:window-testing:1.2.0")
        api("androidx.window.extensions.core:core:1.0.0")
        val workVersion = "2.9.0"
        api("androidx.work:work-runtime-ktx:$workVersion")
        api("androidx.work:work-gcm:$workVersion")
        api("androidx.work:work-testing:$workVersion")
        api("androidx.work:work-multiprocess:$workVersion")
        val acraVersion = "5.11.3"
        api("ch.acra:acra-advanced-scheduler:$acraVersion")
        api("ch.acra:acra-core:$acraVersion")
        api("ch.acra:acra-dialog:$acraVersion")
        api("ch.acra:acra-http:$acraVersion")
        api("ch.acra:acra-limiter:$acraVersion")
        api("ch.acra:acra-mail:$acraVersion")
        api("ch.acra:acra-notification:$acraVersion")
        api("ch.acra:acra-toast:$acraVersion")
        api("com.airbnb.android:lottie:6.2.0")
        api("com.github.bumptech.glide:glide:4.16.0")
        api("com.github.PhilJay:MPAndroidChart:v3.1.0")
        val accompanistVersion = "0.32.0"
        api("com.google.accompanist:accompanist-drawablepainter:$accompanistVersion")
        api("com.google.accompanist:accompanist-permissions:$accompanistVersion")
        api("com.google.accompanist:accompanist-systemuicontroller:$accompanistVersion")
        api("com.google.android.gms:play-services-maps:18.1.0")
        api("com.google.android.libraries.places:places:3.2.0")
        api("com.google.android.material:material:1.10.0")
        api("com.google.code.gson:gson:2.10.1")
        api("com.google.dagger:hilt-android:$hiltVersion")
        api("com.google.dagger:hilt-android-compiler:$hiltVersion")
        api("com.google.dagger:hilt-compiler:$hiltVersion")
        api("com.google.dagger:hilt-android-testing:$hiltVersion")
        api("com.google.devtools.ksp:symbol-processing-api:1.9.21-1.0.15")
        api("com.google.maps.android:maps-compose:2.11.4")
        api("com.google.maps.android:maps-ktx:5.0.0")
        api("com.google.zxing:android-core:3.5.2")
        api("com.google.zxing:android-integration:3.5.2")
        api("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
        api("com.jakewharton.timber:timber:5.0.1")
        api("com.squareup:javapoet:1.13.0")
        api("com.squareup:kotlinpoet:1.15.3")
        api("com.squareup.leakcanary:leakcanary-android:2.12")
        val retrofitVersion = "2.9.0"
        api("com.squareup.retrofit2:adapter-rxjava3:$retrofitVersion")
        api("com.squareup.retrofit2:converter-gson:$retrofitVersion")
        api("com.squareup.retrofit2:converter-jackson:$retrofitVersion")
        api("com.squareup.retrofit2:converter-protobuf:$retrofitVersion")
        api("com.squareup.retrofit2:retrofit:$retrofitVersion")
        api("com.squareup.retrofit2:retrofit-mock:$retrofitVersion")
        api("commons-io:commons-io:2.15.1")
        api("commons-codec:commons-codec:1.16.0")
        api("commons-logging:commons-logging:1.3.0")
        api("io.ktor:ktor-client-android:2.3.6")
        api("io.reactivex.rxjava3:rxjava:3.1.8")
        api("io.reactivex.rxjava3:rxandroid:3.0.2")
        api("junit:junit:4.13.2")
        api("org-apache.commons:commons-lang3:3.14.0")
        api("org-apache.commons:commons-collections4:4.4")
        api("org.aspectj:aspect-core:3.24.2")
        api("org.javassist:javassist:3.30.1-GA")
        api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
        api("org.jooq:jool:0.9.15")
        api("org.jooq:joor:0.9.15")
        api("org.jooq:joor-java-8:0.9.15")
        api("org.jsoup:jsoup:1.17.1")
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            version = project.version.toString()
            from(components.getByName("javaPlatform"))
        }
    }
}
